version: '3.8'
services:
  web:
    image: wrangel/ellesmere:latest
    build: .
    command: "node app.mjs"
    ports:
      - "8080:8080"
    volumes:
      - /Volumes/docker/ellesmere/originals/:/mnt/originals