version: '3.3'
services:
    ellesmere:
        environment:
            - 'DOTENV_KEY=dotenv://:key_39e33a287ff4681e9089e6c055ba1920b7e939e8b698f5520870c55dedcca2d9@dotenv.org/vault/.env.vault?environment=development'
        ports:
            - '8080:8080'
        image: wrangel/ellesmere
        build: .
        command: "node app.mjs"